# Generated by Django 4.1 on 2022-09-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comidas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lanches',
            name='ingredientes',
            field=models.CharField(max_length=300),
        ),
    ]
